name: RWitchWars
version: '${project.version}'
main: ga.justreddy.wiki.rwitchwars.RWitchWars
authors: [JustReddy]
description: Inspired by a dutch server I used to play on.
softdepend:
  - PlaceholderAPI
